version: 2
updates:
  - package-ecosystem: gomod
    directory: "/go/gauge_messages"
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      go:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: monthly
    groups:
      java:
        patterns:
          - "*"