name: Deploy

on: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_SIGN_KEY }}

      - name: Deploy on maven central
        run: mvn -B "-Dstyle.color=always" clean deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.username }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.password }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.passphrase }}
        working-directory: java
